# Generated by Django 2.2.1 on 2019-05-16 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=15)),
                ('phone_number', models.CharField(max_length=20)),
                ('cv', models.FileField(blank=True, upload_to='cv')),
                ('image', models.FileField(blank=True, upload_to='profile_pics')),
                ('radio', models.CharField(max_length=15)),
                ('radio1', models.CharField(max_length=15)),
                ('radio2', models.CharField(max_length=15)),
                ('text', models.CharField(max_length=200)),
            ],
        ),
    ]
