# Generated by Django 2.2.1 on 2019-05-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userform',
            name='email',
            field=models.EmailField(max_length=15),
        ),
    ]
